package com.nutrition.API_nutrition.exception;

/**
 * Permet de centraliser les codes erreurs retourné au client
 */
public enum ErrorCode {
    INVALID_USER_ID,
    INVALID_USER_DATA,
    USER_ROLE_ASSIGNMENT_FAILED,
    AUTHENTICATED_BAD_REQUEST,
    DB_USER_NOT_FOUND,
    DB_SYSTEM_ERROR,
    DB_CONSTRAINT_VIOLATION,
    DB_ERROR,
    TECHNICAL_ERROR,
    BAD_REQUEST_PARAMETER,
    AUTH_JWT_ERROR,
    AUTH_MALFORMED_TOKEN,
    AUTH_INVALID_AUDIENCE,
    AUTH_INVALID_SIGNATURE_OR_ISSUER,
    AUTH_EXPIRED_TOKEN,
    AUTH_JWK_RETRIEVAL_ERROR,
    AUTH_MISSING_TOKEN,
    AUTH_GENERIC_ERROR
}
